development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: raghuteja_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: raghuteja_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: raghuteja_production
  pool: 5
  username: root